### ISSUE TITLE
rlwrap installed; dust does not start

### ISSUE THREAD

**Issue by mathpunk** [pixie-lang/dust#15]
I read issue #2 and the suggestion was to install rlwrap. I have rlwrap installed (on Debian), and yet starting `dust repl` gives me instructions on the usage of rlwrap. Dust does appear on my path.

**Comment by heyLu** [comment]
Can't reproduce that locally, can you send the exact output you get?

It sounds a bit as if your `rlwrap` doesn't support the flags we use, or something like that. Which version of `rlwrap` do you have installed?

**Comment by mathpunk** [comment]
It's version 0.41. The output is not very useful: "Usage: rlwrap [options] command ..." followed by a menu of options and the project website. Note that it's been a couple of weeks since I built pixie.

**Comment by mathpunk** [comment]
Hm, and `./examples/hello-world.pxi` gets me 
    bash: ./hello-world.pxi: ./pixie-vm: bad interpreter: No such file or directory

so maybe I do have some path issues...?

**Comment by heyLu** [comment]
It does sound like path issues, yes. Try the following things:

- in your pixie checkout, run `./pixie-vm`. it should start the repl
- ensure that `pixie-vm` and `dust` are linked to somewhere in your `$PATH`, as [described here](https://github.com/pixie-lang/dust#installation)
- maybe compile pixie again if it doesn't help

**Comment by mathpunk** [comment]
I missed the bit about linking pixie-vm and that did the trick. Thanks for your help.

**Comment by heyLu** [comment]
No problem, have fun! :)
