### ISSUE TITLE
Recur not throwing exception

### ISSUE THREAD

**Issue by biellls** [pixie-lang/dust#26]
The following code should throw an exception because recur is not called from a tail position. Instead it always returns 1.
```clojure
(defn factorial [n]
  (if (zero? n)
    1
    (* n (recur (dec n)))))
```

**Comment by heyLu** [comment]
This also seems to happen in `pixie-vm`, so it's not specific to `dust`.  Can you open an issue on pixie itself?

**Comment by biellls** [comment]
Sorry, my mistake. I meant to post it there.

**Comment by heyLu** [comment]
No worries.  For anyone following along, the issue is pixie-lang/pixie#440.
