### ISSUE TITLE
[PROPOSAL] Don't replicate Leinigen's project structure

### ISSUE THREAD

**Issue by arrdem** [pixie-lang/dust#4]
I would propose that, rather than replicating leinigen's `defproject` form, that instead Dust take a more data driven approach to project specification while we/you still have the chance.

Defproject is nice and familiar to be sure, however I would argue that we can pack all the same information into a simple map (which is what leiningen builds internally anyway). Furthermore, as such a map is data and data alone it becomes easier to automatically manipulate project files with external tools.

Just an idea I've been kicking around since Dust was proposed. I don't have time right now to hammer out a patch (finals are next week) but I'd be curious to see what y'all think of this.

**Comment by spicydonuts** [comment]
Maybe take a little inspiration from [Boot](https://github.com/boot-clj/boot) where Leiningen is lacking

**Comment by heyLu** [comment]
I've created a pull-request that uses a `project.edn` file instead of our current `defproject` approach.

Feel free to play with it for a bit. (Everything should be the same, but with the nice feeling knowing that the system is more declarative. :)

**Comment by heyLu** [comment]
I've just merged #14, so I'm closing this issue now.
